service: BritishMountainsAPI
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
functions:
  hello:
    handler: dist/src/lambda/hello/index.handler
    events:
      - http:
          path: hello
          method: get
          cors: true
  get:
    handler: dist/src/lambda/get/index.handler
    events:
      - http:
          path: get
          method: get
          cors: true
  listing:
    handler: dist/src/lambda/listing/index.handler
    events:
      - http:
          path: listing
          method: get
          cors: true
  search:
    handler: dist/src/lambda/search/index.handler
    events:
      - http:
          path: search
          method: get
          cors: true
  import:
    handler: dist/src/lambda/import/index.handler

plugins:
  - serverless-offline
disabledDeprecations:
  - LAMBDA_HASHING_VERSION_V2

#########################################################################################
## Resource Dynamo DB , S3
#########################################################################################
resources: # CloudFormation template syntax from here on.
  Resources:
    Mountain:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Mountain
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: name
            AttributeType: S
          - AttributeName: label
            AttributeType: S
          - AttributeName: metres
            AttributeType: N
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

        GlobalSecondaryIndexes:
          - IndexName: Index-sk-metres
            KeySchema:
              - AttributeName: sk
                KeyType: HASH
              - AttributeName: metres
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

          # - IndexName: Index-sk-label
          #   KeySchema:
          #     - AttributeName: sk
          #       KeyType: HASH
          #     - AttributeName: label
          #       KeyType: RANGE
          #   Projection:
          #     ProjectionType: ALL
          #   ProvisionedThroughput:
          #     ReadCapacityUnits: 1
          #     WriteCapacityUnits: 1
